add function to generate a free port in the range
orange-cloudfoundry/cf-redis-broker pull request #2
Opened 2016-11-21 13:19 UTC by ZiedZinelabidine

Add function to generate a free port in the range

2016-11-21 14:43 UTC, gberche-orange requested changes
Please include the missing improvements, possibly with the help of @ArthurHlt

2016-11-21 14:43 UTC, gberche-orange commented on system/free_tcp_port.go
> +        toto := ":" + t
consider renaming variable toto into laddr as in the prototype of Net.Listen https://golang.org/pkg/net/#Listen

2016-11-21 14:43 UTC, gberche-orange commented on system/free_tcp_port_test.go
> +
Missing test case "returns an error if no free TCP port in the range"

2016-11-21 14:43 UTC, gberche-orange commented on system/free_tcp_port_test.go
> +        . "github.com/onsi/gomega"
Likely to have indentation issues. Please fix this, the diff is easier to read if only your changes show up.

2016-11-24 15:42 UTC, gberche-orange commented on system/free_tcp_port.go
> +        port, err :=FindFreePort(i)
Please consider returning an error if the user mis configures a max smaller than the min parameter
& add a test case to cover it.

2016-11-24 15:42 UTC, gberche-orange commented on system/free_tcp_port.go
> +        i := Minport
consider reordering parameter so that min is the 1st param, and max the 2nd param

2016-11-24 15:45 UTC, gberche-orange commented on redis/local_instance_creator.go
> +	FindFreePort       func(int) (int, error)
Reconsider removing the declaration in the struct which is not used anymore.

2016-11-24 19:00 UTC, ArthurHlt commented
All unit tests are OK. 
I did some refactoring to be able to test every use case

2016-11-25 08:01 UTC, gberche-orange commented on system/free_tcp_port.go
> +	for port < maxport {
Minor case remaining to cover when minport=maxport, it should return a single port if available.

2016-11-25 08:03 UTC, gberche-orange approved these changes

2016-11-25 08:14 UTC, gberche-orange commented
Thanks @ArthurHlt and @ZiedZinelabidine. Last changes look good to me (with the minor suggestion in https://github.com/orange-cloudfoundry/cf-redis-broker/pull/2#pullrequestreview-10120895 )

How do configuration errors or missing ports appear to bosh operators ? 
- would the bosh deployment nicely failing, and broker logs contain a trace with the error log ?
- would shared port misconfigurations only be detected at binding time, failing service binding ?

Please consider refining the PR text to illustrate how operators will discover such errors, and potentially propose/implement further enhancements to check config at broker start time.

Feel free then to merge (and squash commits) and submit pr against pivotal-cf/cf-redis-broker master (or possibly include minor

2016-11-25 16:54 UTC, ArthurHlt commented
I've finally run integration tests, Everything looks good.

About errors:
- during configuration loading if ports are misconfigured it will report directly report the error. 
- When the service broker try to find a free port during provisioning and no port is available in the range it will give a service broker error. This error will ask to the user to contact his operator.

2016-12-08 10:49 UTC, gberche-orange commented
Thanks @ArthurHlt for your contribution to unit tests and input validation in the configuration. Please merge and squash so that commits appear from your id.

2016-12-08 10:56 UTC, merged